### ISSUE TITLE
Todo: check free memory before playing

### ISSUE THREAD

**Issue by FrankBoesing** [FrankBoesing/Arduino-Teensy-Codec-lib#1]
FLAC can have very harsh RAM requirements at blocksize > 1024
First, have to figure out how to get frameinfo before starting first frame.. at first sight, there is no api-call (?!?)

Good for MP3+AAC too.

**Comment by t413** [comment]
I'm blown away at how much work you've put into this. Most impressive and excellent! Thanks for your work, and I'll see if there's any way I can contribute too.
