### ISSUE TITLE
Teensy LC + Prop Shield LC not supported?

### ISSUE THREAD

**Issue by ramgarden** [FrankBoesing/Arduino-Teensy-Codec-lib#10]
Getting this error when compiling for the Teensy LC + Prop Shield LC:
Documents\Arduino\libraries\Arduino-Teensy-Codec-lib-master/play_sd_mp3.h:44:0
Documents\Arduino\libraries\Arduino-Teensy-Codec-lib-master/codecs.h:40:2: error: #error This platform is not supported.

**Comment by FrankBoesing** [comment]
Correct.
LC is not supported due to too less RAM.
