### ISSUE TITLE
Playing files from different sources

### ISSUE THREAD

**Issue by Stass48** [FrankBoesing/Arduino-Teensy-Codec-lib#22]
Hello, Now audio library use sdfat, but I can't play file from sdfat card, because method play(); haven't SdFs argument. For example:

```
SdFs card1;
SdFs card2;
...

Mp3player.play(&card1, "test.mp3");
```

I get many warnings while compiling and the code not working.

How to chose source sd card for playing files if I have two or more sd cards on one teensy?

Thank you.

**Comment by FrankBoesing** [comment]
https://github.com/PaulStoffregen/Audio/issues/354
