### ISSUE TITLE
Read file metadata tag info

### ISSUE THREAD

**Issue by t413** [FrankBoesing/Arduino-Teensy-Codec-lib#4]
Hey! I'm blown away at how well done this is. One thing I can imagine being a major enhancement: ID3 tag reading support.

I wrote this project some 5 years ago now and it might be something workable to include/revise/rewrite: [t413/read_ID3_info](https://github.com/t413/read_ID3_info).

I'll go through it tomorrow and see how well it still works and look at AAC tags. Another possible library is (taglib)[http://taglib.github.io].

**Comment by FrankBoesing** [comment]
Hi,

you're welcome :-)

If you could do the ID3-reader this would be a great help.
We need to talk about the API before!

Regards, Frank

Am 15.01.2015 um 10:27 schrieb t413:
