### ISSUE TITLE
can't play multiple mp3 files at the same time

### ISSUE THREAD

**Issue by bohbotjames** [FrankBoesing/Arduino-Teensy-Codec-lib#9]
Hello, I'd like to be able to play many different mp3 files on my teensy 3.6 and then route them through mixers to listen to them at the same time. the problem is that when I put more than 1 AudioPlaySdMp3 in my code, the music just won't play. Here is an example code:

`
#include <Audio.h>
#include <Wire.h>
#include <SPI.h>
#include <SD.h>

#include <play_sd_mp3.h>

// GUItool: begin automatically generated code
AudioPlaySdMp3           playMp31, playMp32;       //xy=154,78
AudioOutputI2S           i2s1;           //xy=334,89
AudioConnection          patchCord1(playMp31, 0, i2s1, 0);
AudioConnection          patchCord2(playMp31, 1, i2s1, 1);
AudioControlSGTL5000     sgtl5000_1;     //xy=240,153
// GUItool: end automatically generated code

void setup() {
  Serial.begin(9600);

  // Audio connections require memory to work.  For more
  // detailed information, see the MemoryAndCpuUsage example
  AudioMemory(5);

  sgtl5000_1.enable();
  sgtl5000_1.volume(0.5);

  SPI.setMOSI(7);
  SPI.setSCK(14);
  if (!(SD.begin(10))) {
    // stop here, but print a message repetitively
    while (1) {
      Serial.println("Unable to access the SD card");
      delay(500);
    }
  }

  
  playMp31.play("canada.mp3");
  playMp32.play("france.mp3"); // both of these tunes won't play, but if i comment the seccond one,
                               // then the other plays fine.
}

void loop() {
  delay(100);
}
`

**Comment by NullMember** [comment]
Do you tried to change audio memory? 5 is maybe not enough for playing multiple mp3 files at once.
